### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by mgaulton** [BackSlasher/deluge_framework#3]
So i'm trying to recreate some scripting I had for uTorrent with Deluge, where i have files of text phrases that I convert to regex, then manipulate the torrent list.
I'm trying to figure out how to leverage your code, as it seems to be at least partway to what I need.

I have a blacklist, a whitelist, and category based lists.
in the code, there are multiple actions
```
I have a blacklist, a whitelist, and category based lists.
in the code, there are multiple actions

Loop through torrent list:
        Loop through tvlist:
	   if <tv regex> and size > x:
	       delete torrent
	Loop through each lable phrase list:
		if <any label key> in tname:
		    assign label 
	Loop through blacklist phrases:
		if <blacklist phrase> in tname:
			loop through whitelist phrases:
				if no matches in whitelist, delete torrent



```

Any pointers on how to accomplish this?

**Comment by BackSlasher** [comment]
Hi! Happy to hear someone is using this.
I don't think I have a way to assign labels in this library (will happy to accept PRs).
The deletion part can be implemented by copying off one of my examples, and using an `if` to decide whether to return `d` (delete torrent) or `` (do nothing).
How does that sound?

**Comment by mgaulton** [comment]
I can live without the labels, since the autoadd allows multiple import folders, unlike uT. 

Sounds like that could work.  I'm guessing I put everything basically into torrentAction and filterTorrents will get the list and loop it.

**Comment by mgaulton** [comment]
How do i get a torrent, process, then move to the next? 
does the filter_torrents get a collection and then call torrentAction for each in order?
i don't want to run this and have in call torrentAction once for the whole list or return the value only ones because torrentAction gets the whole collection.

**Comment by BackSlasher** [comment]
If you'll look at one of the examples:
https://github.com/BackSlasher/deluge_framework#print-progress-and-state-for-all-torrents
The function you're writing, `torrentAction`, is called once per torrent and returns the action for this torrent.

**Comment by mgaulton** [comment]
Ahh it queues them till the end then runs through teh actions. Thanks. I *tink* i got it working. running a full run now.

**Comment by mgaulton** [comment]
So this seems to work for what I needed. Many thanks.
If you ever feel the urge to expand it.

1. Label setting
2. Queue priority setting
3. pause by api

**Comment by BackSlasher** [comment]
Happy to hear! I'm not actively working on this right now, but they have this fancy feature here where you can copy over the code, add any functionality you want, and post a request for me to merge your code back here, so other people can benefit from it.
Consider it :smile:
