### ISSUE TITLE
Passed value issue

### ISSUE THREAD

**Issue by mgaulton** [BackSlasher/deluge_framework#4]
Hey There, 
I'm extending your code to do some of the other stuff that I talked to you about previous and running into an odd issue.  Trying to manage jobs in the queue, so 'category = first, queue to top' and its doing this odd thing where the RPC error shows the full value for the passed torrent_id but gives a key error of u'<first char of torrent_id>'. Not sure why, its looks the same as the others and they don't have issues.
Initially, it complained about the number of arguments so I removed the boolean and just pass the torrent_id as per the docs at http://deluge.readthedocs.io/en/develop/core/rpc.html.

Any help would be appreciated.

  successmsg = "%s [%s]: Deleted without data" % (torrent_id, torrent_info['name'])
                errormsg = "%s [%s]: Error deleting without data" % (torrent_id, torrent_info["name"])
                tlist.append(client.core.queue_top(torrent_id).addCallbacks(printSuccess, printError, callbackArgs = (True, successmsg), errbackArgs = (errormsg)))

ERROR:deluge.ui.client:RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: core.queue_top(0fe7ff85027e9c6e5d4248483f4663160435fee9)
--------------------------------------------------------------------------------
KeyError
u'0': Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/deluge-2.0b2.dev43-py2.7.egg/deluge/core/rpcserver.py", line 302, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/deluge-2.0b2.dev43-py2.7.egg/deluge/core/core.py", line 975, in queue_top
    for torrent_id in sorted(torrent_ids, key=self.torrentmanager.get_queue_position, reverse=True):
  File "/usr/lib/python2.7/site-packages/deluge-2.0b2.dev43-py2.7.egg/deluge/core/torrentmanager.py", line 963, in get_queue_position
    return self.torrents[torrent_id].get_queue_position()
KeyError: u'0'

**Comment by BackSlasher** [comment]
Hi.
Could you please put your code between three graves?

    ```
    fssdf
    ```

It'll help readability
Thanks!

**Comment by mgaulton** [comment]
```
            elif res2 == 'qt':
                successmsg = "%s [%s]: Deleted without data" % (torrent_id, torrent_info['name'])
                errormsg = "%s [%s]: Error deleting without data" % (torrent_id, torrent_info["name"])
                tlist.append(client.core.queue_top(torrent_id).addCallbacks(printSuccess, printError, callbackArgs = (True, successmsg), errbackArgs = (errormsg)))
```

```
ERROR:deluge.ui.client:RPCError Message Received!
RPCRequest: core.queue_top(0fe7ff85027e9c6e5d4248483f4663160435fee9)
KeyError
u'0': Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/deluge-2.0b2.dev43-py2.7.egg/deluge/core/rpcserver.py", line 302, in dispatch
ret = self.factory.methods[method](*args, **kwargs)
File "/usr/lib/python2.7/site-packages/deluge-2.0b2.dev43-py2.7.egg/deluge/core/core.py", line 975, in queue_top
for torrent_id in sorted(torrent_ids, key=self.torrentmanager.get_queue_position, reverse=True):
File "/usr/lib/python2.7/site-packages/deluge-2.0b2.dev43-py2.7.egg/deluge/core/torrentmanager.py", line 963, in get_queue_position
return self.torrents[torrent_id].get_queue_position()
KeyError: u'0'
```

**Comment by mgaulton** [comment]
Sorry about that, i forgot to do that.
