### ISSUE TITLE
connect params questions

### ISSUE THREAD

**Issue by mgaulton** [BackSlasher/deluge_framework#5]
Using this connect line in the code, i get the following error
    cliconnect = client.connect({"host":"localhost", "port":58847, "username":"myuser","password":"mypass"})
```Traceback (most recent call last):
  File "/opt/deluge.blackpron.py", line 335, in <module>
    filter_torrents({},['name','state','progress','total_size','label'],torrentAction)
  File "/opt/code/deluge_frameworkpron/deluge_frameworkpron.py", line 145, in filter_torrents
    cliconnect = client.connect({"host":"localhost", "port":58847, "username":"master", "password":"maxxdark"})
  File "/opt/deluge/deluge/ui/client.py", line 548, in connect
    d = self._daemon_proxy.connect(host, port)
  File "/opt/deluge/deluge/ui/client.py", line 267, in connect
    ssl.ClientContextFactory())
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 508, in connectSSL
    return self.connectTCP(host, port, tlsFactory, timeout, bindAddress)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 499, in connectTCP
    c = tcp.Connector(host, port, factory, timeout, bindAddress, self)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 1164, in __init__
    if abstract.isIPv6Address(host):
  File "/usr/lib64/python2.7/site-packages/twisted/internet/abstract.py", line 546, in isIPv6Address
    return isIPAddress(addr, AF_INET6)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/abstract.py", line 516, in isIPAddress
    addr = addr.split(u"%", 1)[0]
AttributeError: 'dict' object has no attribute 'split'
```

**Comment by BackSlasher** [comment]
Could you post a bit of the code you're using to call this lib?
Also, note the markdown formatting on your post. It helps increase readability.

**Comment by mgaulton** [comment]
werid, i could have sworn i used markups :(

Which part would you like to see? I'm trying to get a dedicated second
instance of deluge running, so alternate port/config path etc.
Copied the entire project into a new folder, renamed the files and changed
the imports.

How much / which parts do you need to see?
I have some functions that look at phrase lists and assign a result, in
this case, its deleting jobs that hit on a blacklist phrase and then
terminating them.
This is my torrentAction.
filter_torrents({},['name','state','progress','total_size','label'],torrentAction)

**Comment by mgaulton** [comment]
Oh I should add, the only line that I changed from the working script with
the primary instance, was that connect line i pasted at the start of the
issue here.

**Comment by BackSlasher** [comment]
I haven't touched this code in a long time, but it's possible that the deluge API has changed and my call to `connect` is no longer correct. That will explain why the Deluge code is trying to use `str` methods on a `dict`

**Comment by mgaulton** [comment]
OK, i'll poke around a bit and see if i can figure that out. Thanks.
